/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import beans.Emprunt;
import beans.Etudiant;
import beans.Livre;
import java.awt.Color;
import java.awt.Cursor;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;
import services.EmpruntService;
import services.EtudiantService;
import services.LivreService;

public class EmpruntForm extends javax.swing.JInternalFrame {

    private LivreService ls;
    private EtudiantService es;
    private EmpruntService emps;
    private DefaultTableModel model;

    /**
     * Creates new form EmpruntForm
     */
    public EmpruntForm() {
        MDIApplication app = MDIApplication.getInstance();
        initComponents();
        ls = new LivreService();
        es = new EtudiantService();
        emps = new EmpruntService();
        model = (DefaultTableModel) listEmprunt.getModel();
        loadLivre();
        loadEtudiant();
        load();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        listLivreEmprunt = new javax.swing.JComboBox();
        date_Emprunt = new com.toedter.calendar.JDateChooser();
        date_Retour = new com.toedter.calendar.JDateChooser();
        bnSaveEmprunt = new javax.swing.JButton();
        listEtudiantEmprunt = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEmprunt = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMaximumSize(new java.awt.Dimension(1400, 700));
        setMinimumSize(new java.awt.Dimension(400, 100));
        setPreferredSize(new java.awt.Dimension(630, 600));

        jPanel1.setBackground(new java.awt.Color(240, 240, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion des empruns", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Livre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Etudiant:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Date Emprunt:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Date Retour:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        listLivreEmprunt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        listLivreEmprunt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Without My Daughter", "Le Dernier Jour D'un Condmané", "La boîte à merveilles" }));
        jPanel1.add(listLivreEmprunt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));
        jPanel1.add(date_Emprunt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 180, -1));
        jPanel1.add(date_Retour, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 180, -1));

        bnSaveEmprunt.setBackground(new java.awt.Color(0, 204, 51));
        bnSaveEmprunt.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bnSaveEmprunt.setText("Enregistrer");
        bnSaveEmprunt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnSaveEmpruntActionPerformed(evt);
            }
        });
        jPanel1.add(bnSaveEmprunt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, -1));

        listEtudiantEmprunt.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        listEtudiantEmprunt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hiba Bend", "Fati Enn", "Mery Abbadi" }));
        jPanel1.add(listEtudiantEmprunt, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 180, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Capture-removebg-preview (1).png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 180, -1));

        jPanel2.setBackground(new java.awt.Color(240, 240, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste des emprunts", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14))); // NOI18N

        listEmprunt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Livre", "Etudiant", "Date Emprunt", "Date Retour"
            }
        ));
        jScrollPane1.setViewportView(listEmprunt);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(282, 282, 282))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void loadLivre() {
        listLivreEmprunt.removeAllItems();
        for (Livre l : ls.findAll()) {
            listLivreEmprunt.addItem(l);
        }
    }

    void loadEtudiant() {
        listEtudiantEmprunt.removeAllItems();
        for (Etudiant e : es.findAll()) {
            listEtudiantEmprunt.addItem(e);
        }
    }

    private void bnSaveEmpruntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnSaveEmpruntActionPerformed
        Livre livre = (Livre) listLivreEmprunt.getSelectedItem();
        Etudiant etudiant = (Etudiant) listEtudiantEmprunt.getSelectedItem();
        Date dateEmprunt = date_Emprunt.getDate();
        Date dateRetour = date_Retour.getDate();

        if (livre == null || etudiant == null || dateEmprunt == null || dateRetour == null) {
            JOptionPane.showMessageDialog(this, "Veuillez renseigner tous les champs.", "Avertissement", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (emps.create(new Emprunt(dateEmprunt, dateRetour, livre, etudiant))) {
            JOptionPane.showMessageDialog(this, "Emprunt enregistré avec succès!", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Erreur lors de l'enregistrement de l'emprunt.", "Erreur", JOptionPane.ERROR_MESSAGE);
        }

        load();
    }//GEN-LAST:event_bnSaveEmpruntActionPerformed

    void load() {
        model.setRowCount(0);
        for (Emprunt e : emps.findAll()) {
            if (e == null) {
                System.out.println("Avertissement : Un emprunt est null.");
                continue;
            }

            String titreLivre = (e.getLivre() != null) ? e.getLivre().getTitre() : "Livre inconnu";
            String nomEtudiant = (e.getEtudiant() != null) ? e.getEtudiant().getNom() : "Étudiant inconnu";

            model.addRow(new Object[]{
                titreLivre,
                nomEtudiant,
                e.getDateEmprunt(),
                e.getDateRetour()
            });
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnSaveEmprunt;
    private com.toedter.calendar.JDateChooser date_Emprunt;
    private com.toedter.calendar.JDateChooser date_Retour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listEmprunt;
    private javax.swing.JComboBox listEtudiantEmprunt;
    private javax.swing.JComboBox listLivreEmprunt;
    // End of variables declaration//GEN-END:variables
}
