/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import services.UserService;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setTitle("Authetification");
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        bnConnexion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pwdforgotten = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 620));

        jPanel1.setBackground(new java.awt.Color(243, 243, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(660, 590));
        jPanel1.setMinimumSize(new java.awt.Dimension(660, 590));
        jPanel1.setPreferredSize(new java.awt.Dimension(660, 590));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        login.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        login.setForeground(new java.awt.Color(221, 215, 191));
        login.setText("Login:");
        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 61, 29));

        password.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(221, 215, 191));
        password.setText("Mot De Passe:");
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, -1));
        jPanel1.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 290, 33));
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 290, 35));

        bnConnexion.setBackground(new java.awt.Color(212, 194, 168));
        bnConnexion.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        bnConnexion.setText("Connexion");
        bnConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnConnexionActionPerformed(evt);
            }
        });
        jPanel1.add(bnConnexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 460, 116, 42));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 44, -1, -1));

        pwdforgotten.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        pwdforgotten.setForeground(new java.awt.Color(215, 201, 183));
        pwdforgotten.setText("Mot de passe oublié?");
        pwdforgotten.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwdforgottenMouseClicked(evt);
            }
        });
        jPanel1.add(pwdforgotten, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(955, 825, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 204, 102));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-utilisateur-50 (1).png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-mot-de-passe-48 (1).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/backmain.PNG"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnConnexionActionPerformed
        String login = txtLogin.getText().trim();
        String password = new String(txtPassword.getPassword()).trim();

        UserService userService = new UserService();

        if (userService.authenticate(login, password)) {
            MDIApplication mdi = MDIApplication.getInstance();
            mdi.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Login ou mot de passe incorrect", "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bnConnexionActionPerformed

    private void pwdforgottenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdforgottenMouseClicked
        String login = txtLogin.getText().trim();
        UserService userService = new UserService();

        String email = JOptionPane.showInputDialog(this, "Entrez votre adresse email");

        if (userService.userExists(login) && email != null && !email.isEmpty()) {

            String reponseSecrete = JOptionPane.showInputDialog(this, "Quelle est le nom de votre animal de compagnie ?");
            String bonneReponse = "Ares";

            if (reponseSecrete != null && reponseSecrete.trim().equalsIgnoreCase(bonneReponse)) {

                String nouveauMotDePasse = JOptionPane.showInputDialog(this, "Entrez votre nouveau mot de passe");

                if (nouveauMotDePasse != null && !nouveauMotDePasse.trim().isEmpty()) {
                    boolean result = userService.changerMotDePasse(login, nouveauMotDePasse);

                    Properties properties = new Properties();
                    properties.put("mail.smtp.host", "smtp.gmail.com");
                    properties.put("mail.smtp.port", "587");
                    properties.put("mail.smtp.starttls.enable", "true");
                    properties.put("mail.smtp.auth", "true");

                    Session session = Session.getInstance(properties, new Authenticator() {
                        @Override
                        protected PasswordAuthentication getPasswordAuthentication() {
                            return new PasswordAuthentication("h.bendriouich@elaraki.ac.ma", "wvpi jomp bzhs pmem");
                        }
                    });

                    try {

                        Message message = new MimeMessage(session);
                        message.setFrom(new InternetAddress("h.bendriouich@elaraki.ac.ma"));
                        message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(email));
                        message.setSubject("Récupération de mot de passe");
                        String messageContent = "Bonjour "+login+" ,\n\nVotre nouveau mot de passe est : " + nouveauMotDePasse;
                        message.setText(messageContent);

                        Transport.send(message);

                        if (result) {
                            JOptionPane.showMessageDialog(this, "Mot de passe changé avec succès !");
                            JOptionPane.showMessageDialog(this, "Votre nouveau mot de passe a été envoyé à votre adresse email.");
                        } else {
                            JOptionPane.showMessageDialog(this, "Échec du changement de mot de passe.");
                        }

                    } catch (MessagingException e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Échec de l'envoi du mot de passe. Vérifiez l'adresse email.");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Le mot de passe ne peut pas être vide.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Réponse incorrecte à la question secrète.");
            }
        } else {
            JOptionPane.showMessageDialog(this, "L'adresse email ne peut pas être vide ou l'utilisateur est inconnu.");
        }
    }//GEN-LAST:event_pwdforgottenMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnConnexion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel login;
    private javax.swing.JLabel password;
    private javax.swing.JLabel pwdforgotten;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
