/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JInternalFrame;

public class MDIApplication extends javax.swing.JFrame {

    private static MDIApplication instance;

    /**
     * Creates new form MDIApplication
     */
    public MDIApplication() {
        initComponents();
        this.setTitle("Gestion des emprunts de livres");
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    public synchronized static MDIApplication getInstance() {
        if (instance == null) {
            instance = new MDIApplication();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        etudiantMenuItem = new javax.swing.JMenuItem();
        LivreMenuItem = new javax.swing.JMenuItem();
        saveAsMenuEmprunts = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        rechercheMenuItem = new javax.swing.JMenuItem();
        FiltrerMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(215, 235, 255));

        menuBar.setBackground(new java.awt.Color(204, 255, 255));
        menuBar.setMaximumSize(new java.awt.Dimension(300, 32769));

        Menu.setMnemonic('f');
        Menu.setText("Gestion");

        etudiantMenuItem.setMnemonic('o');
        etudiantMenuItem.setText("Etudiants");
        etudiantMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                etudiantMenuItemActionPerformed(evt);
            }
        });
        Menu.add(etudiantMenuItem);

        LivreMenuItem.setMnemonic('s');
        LivreMenuItem.setText("Livres");
        LivreMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LivreMenuItemActionPerformed(evt);
            }
        });
        Menu.add(LivreMenuItem);

        saveAsMenuEmprunts.setMnemonic('a');
        saveAsMenuEmprunts.setText("Emprunts");
        saveAsMenuEmprunts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuEmpruntsActionPerformed(evt);
            }
        });
        Menu.add(saveAsMenuEmprunts);

        menuBar.add(Menu);

        editMenu.setMnemonic('e');
        editMenu.setText("Recherche");

        rechercheMenuItem.setText("Rechercher un livre par auteur");
        rechercheMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(rechercheMenuItem);

        FiltrerMenuItem.setMnemonic('t');
        FiltrerMenuItem.setText("Filtrer les emprunts par date");
        FiltrerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltrerMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(FiltrerMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Contents");
        helpMenu.add(contentMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void etudiantMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_etudiantMenuItemActionPerformed
        closeAllInternalFrames();
        EtudiantForm ef = new EtudiantForm();
        desktopPane.add(ef);
        ef.setVisible(true);
    }//GEN-LAST:event_etudiantMenuItemActionPerformed

    private void LivreMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LivreMenuItemActionPerformed
        closeAllInternalFrames();
        LivreForm lf = new LivreForm();
        desktopPane.add(lf);
        lf.setVisible(true);
    }//GEN-LAST:event_LivreMenuItemActionPerformed

    private void saveAsMenuEmpruntsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAsMenuEmpruntsActionPerformed
        closeAllInternalFrames();
        EmpruntForm empf = new EmpruntForm();
        desktopPane.add(empf);
        empf.setVisible(true);
    }//GEN-LAST:event_saveAsMenuEmpruntsActionPerformed

    private void rechercheMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheMenuItemActionPerformed
        closeAllInternalFrames();
        RechercheLivreAuteurForm r = new RechercheLivreAuteurForm();
        desktopPane.add(r);
        r.setVisible(true);

    }//GEN-LAST:event_rechercheMenuItemActionPerformed

    private void FiltrerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltrerMenuItemActionPerformed
        closeAllInternalFrames();
        FilterEmpruntForm f = new FilterEmpruntForm();
        desktopPane.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_FiltrerMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MDIApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MDIApplication().setVisible(true);
            }
        });
    }

    private void closeAllInternalFrames() {
        for (JInternalFrame frame : desktopPane.getAllFrames()) {
            frame.dispose();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem FiltrerMenuItem;
    private javax.swing.JMenuItem LivreMenuItem;
    private javax.swing.JMenu Menu;
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem etudiantMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem rechercheMenuItem;
    private javax.swing.JMenuItem saveAsMenuEmprunts;
    // End of variables declaration//GEN-END:variables

}
